Models/ErrorViewModel.cs
using System;

namespace UnicornRanch.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UnicornLocationModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UnicornRanch.Models
{
    // Basic model to represent a unicorn's possible location at any given time
    // Multiple Unicorns may be at the same location
    public class UnicornLocationModel
    {
        [Key]
        public int id { get; set; }
        [DisplayName("Current Location")]
        public string LocationName { get; set; }

    }
}

Models/UnicornModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UnicornRanch.Models
{
    // Basic model to represent a unicorn
    public class UnicornModel
    {
        [Key]
        public int id { get; set; }
        [DisplayName("Unicorn Name")]
        public string UnicornName { get; set; }
        [DisplayName("Color")] 
        public string Color { get; set; }
        [DisplayName("Favorite Snack")] 
        public string FavoriteSnack { get; set; }
        public UnicornLocationModel CurrentLocation { get; set; }

    }
}

Controllers/UnicornModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UnicornRanch.Data;
using UnicornRanch.Models;

namespace UnicornRanch.Controllers
{
    public class UnicornModelsController : Controller
    {
        private readonly UnicornFarmDbContext _context;

        public UnicornModelsController(UnicornFarmDbContext context)
        {
            _context = context;
        }

        // GET: UnicornModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.unicorns
                .Include(u=>u.CurrentLocation).ToListAsync());
        }

        // GET: UnicornModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unicornModel = await _context.unicorns
                .Include(u => u.CurrentLocation)
                .FirstOrDefaultAsync(u => u.id == id);
            if (unicornModel == null)
            {
                return NotFound();
            }

            return View(unicornModel);
        }


        // Add seed data if needed when this endpoint gets hit
        // Will added canned unicorns and their associated locations
        public IActionResult SeedData()
        {
            string seedResponseMsg = "Database already has been seeded"; // Default response message

            // If there arent any unicorns seed the database
            if (!_context.unicorns.Any())
            {

                var newLocations = new List<UnicornLocationModel>
                {
                    new UnicornLocationModel() { id=1, LocationName = "Barn"},
                    new UnicornLocationModel() { id=2, LocationName = "Pasture"},
                    new UnicornLocationModel() { id=3, LocationName = "Magical Training Area 1"},
                    new UnicornLocationModel() { id=4, LocationName = "Combat Training Area 2"},
                    new UnicornLocationModel() { id=5, LocationName = "The Local Pub"}
                };
                _context.AddRange(newLocations); // add our possible unicorn locations
                // Save our locations 
                _context.SaveChanges();

                var newUnicorns = new List<UnicornModel>
                {
                    new UnicornModel() { id=1, UnicornName = "Afghanistan",Color = "Brown",FavoriteSnack="Candy",CurrentLocation=_context.locations.FirstOrDefault(location=>location.id==1)},
                    new UnicornModel() { id=2, UnicornName = "Bob",Color = "Yellow",FavoriteSnack="Corn", CurrentLocation=_context.locations.FirstOrDefault(location=>location.id==3)},
                    new UnicornModel() { id=3, UnicornName = "Jane",Color = "White",FavoriteSnack="Other Unicorns", CurrentLocation=_context.locations.FirstOrDefault(location=>location.id==5)},
                };
                _context.AddRange(newUnicorns); // add our unicorns
                // Save our unicorns
                _context.SaveChanges();
                seedResponseMsg = "Seeded the database with new Unicorns and Locations";
            }
            // Return simple result message
            return Content(seedResponseMsg);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Unicorn Ranch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="UnicornModels" asp-action="Index">Unicorn Ranch</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Unicorn Ranch
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/UnicornModels/Details.cshtml
@model UnicornRanch.Models.UnicornModel

@{
    ViewData["Title"] = "Unicorn Details";
}

<h1>Details for Unicorn @Model.UnicornName</h1>

<div>
    <h4>UnicornModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UnicornName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UnicornName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FavoriteSnack)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FavoriteSnack)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentLocation.LocationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CurrentLocation.LocationName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to Unicorn List</a>
</div>

Views/UnicornModels/Index.cshtml
@model IEnumerable<UnicornRanch.Models.UnicornModel>

@{
    ViewData["Title"] = "All of our Unicorns";
}

<h1>All of our Unicorns</h1>
@*TODO: Generated Index provides a skeleton HTML table but probably want to display differently in the future*@
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UnicornName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FavoriteSnack)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentLocation.LocationName)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.id">@item.UnicornName</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FavoriteSnack)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentLocation.LocationName)
            </td>
        </tr>
}
    </tbody>
</table>